name: Clippy and check

on:
  push:

jobs:
  lint-and-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo check
        run: cargo check --all --all-targets --all-features

      - name: Run cargo clippy
        run: cargo clippy --all --all-targets --all-features -- -D warnings
